New feature/ccp 247
diging/conceptpower pull request #197
Opened 2019-03-12 18:05 UTC by abhis1989kumar

2019-03-12 21:12 UTC, jdamerow commented
there seem to be a bunch of review request classes in this branch that do not belong to this ticket. please remove.

2019-03-18 16:30 UTC, jdamerow requested changes

2019-03-18 16:30 UTC, jdamerow commented on Conceptpower+Spring/pom.xml
> +					<server>TomcatServer</server>
this needs to be configurable, hence the variable

2019-03-18 16:30 UTC, jdamerow commented on Conceptpower+Spring/src/main/java/edu/asu/conceptpower/app/jaxb/viaf/Channel.java
> +    @XmlElement(name = "item")
indentation

2019-03-18 16:30 UTC, jdamerow commented on Conceptpower+Spring/src/main/java/edu/asu/conceptpower/app/profile/impl/ViafService.java
> +		ViafReply rep = reply.getBody();
formatting

2019-03-18 16:30 UTC, jdamerow commented on Conceptpower+Spring/src/main/resources/log4j.xml
> +		<level value="debug" />
let's set that to info

2019-03-18 16:30 UTC, jdamerow commented on Conceptpower+Spring/src/main/resources/log4j.xml
> +		<level value="debug" />
actually, let's use ${debug_level} for all debugger

2019-03-18 16:30 UTC, jdamerow commented on Conceptpower+Spring/src/main/webapp/WEB-INF/spring/db4o-config.xml
> +	</bean>
does not belong into this pull request

2019-03-18 16:30 UTC, jdamerow commented on Conceptpower+Spring/src/main/webapp/WEB-INF/views/home.jsp
> +	<meta name="_csrf_header" content="${_csrf.headerName}"/>
indentation

2019-03-18 16:30 UTC, jdamerow commented on Conceptpower+Spring/src/main/webapp/WEB-INF/views/nav/showresults.jsp
> +</html>
what is this page for?

2019-03-18 16:30 UTC, jdamerow commented on Conceptpower+Spring/src/test/java/edu/asu/conceptpower/profile/impl/ViafServiceTest.java
> +        assertEquals("Pirckheimer TIB X Kommentar.1001.106 C6", searchResults.get(0).getName());
how can set be? the search result set up on top returns something else?

2019-03-20 00:59 UTC, jdamerow requested changes
please address all my previous comments before I finish reviewing

2019-03-20 00:59 UTC, jdamerow commented on Conceptpower+Spring/pom.xml
> +					<server>${tomcat.server}</server>
that's not the right property

2019-03-20 00:59 UTC, jdamerow commented on Conceptpower+Spring/src/main/java/edu/asu/conceptpower/app/jaxb/viaf/Channel.java
> +    @XmlElement(name = "item")
?

2019-03-21 21:32 UTC, jdamerow requested changes

2019-03-21 21:32 UTC, jdamerow commented on Conceptpower+Spring/pom.xml
> +				<tomcat.server>localhost</tomcat.server>
Oh, I didn't realize you've added those. In that case please delete them.

2019-03-21 21:32 UTC, jdamerow commented on Conceptpower+Spring/src/main/java/edu/asu/conceptpower/app/profile/impl/ViafService.java
> +		String fullUrl="";
declare when needed

2019-03-21 21:32 UTC, jdamerow commented on Conceptpower+Spring/src/test/java/edu/asu/conceptpower/profile/impl/ViafServiceTest.java
> +    private RestTemplate restTemplate;
there are two restTemplates now, but I would think you only need one

2019-03-21 21:32 UTC, jdamerow commented on Conceptpower+Spring/src/test/java/edu/asu/conceptpower/profile/impl/ViafServiceTest.java
> +        }
duplicate code (line 80-89)?

2019-03-21 21:32 UTC, jdamerow commented on Conceptpower+Spring/src/test/resources/log4j.xml
> +		<level value="debug" />
let's use the pom property here, we don't want it to always debug

2019-04-03 21:48 UTC, jdamerow commented on Conceptpower+Spring/src/test/java/edu/asu/conceptpower/profile/impl/ViafServiceTest.java
> +    private RestTemplate restTemplate;
?

2019-04-03 21:51 UTC, jdamerow commented
my previous comments don't seem to be addressed.

2019-04-08 19:10 UTC, jdamerow requested changes

2019-04-08 19:10 UTC, jdamerow commented on Conceptpower+Spring/src/test/java/edu/asu/conceptpower/profile/impl/ViafServiceTest.java
> +          MockitoAnnotations.initMocks(this);
indentation?

2019-04-08 19:10 UTC, jdamerow commented on Conceptpower+Spring/src/test/java/edu/asu/conceptpower/profile/impl/ViafServiceTest.java
> +        }
?

2019-04-09 19:38 UTC, jdamerow commented
Jenkins, run integration tests please

2019-04-09 19:57 UTC, jdamerow commented
Jenkins, run integration tests please

2019-04-09 19:59 UTC, jdamerow commented on Conceptpower+Spring/pom.xml
> +			<version>8.0.276.16149</version>
please do not change that version

2019-04-10 16:52 UTC, jdamerow commented
integration tests are failing, please fix

2019-10-09 17:42 UTC, jdamerow commented
Jenkins, run integration tests please

2019-10-11 13:29 UTC, jdamerow commented
Jenkins, run integration tests please

2019-10-11 13:34 UTC, jdamerow commented
Jenkins, run integration tests please

2019-10-11 14:42 UTC, jdamerow commented
I don't know why the integration tests pass locally but not on Jenkins, but the issue is that something goes wrong with the indexing. The tests that fail, fail because of this exception:
```
ERROR: edu.asu.conceptpower.web.util.ExceptionHandler - ExceptionHandler caught exception.
java.lang.IllegalStateException: field "listName" was indexed without position data; cannot run PhraseQuery (phrase=listName:"vogonweb concepts")
	at org.apache.lucene.search.PhraseQuery$PhraseWeight.scorer(PhraseQuery.java:430)
	at org.apache.lucene.search.BooleanWeight.scorer(BooleanWeight.java:280)
	at org.apache.lucene.search.Weight.bulkScorer(Weight.java:135)
	at org.apache.lucene.search.BooleanWeight.bulkScorer(BooleanWeight.java:262)
```
If you add ```.param("concept_list", "VogonWeb Concepts")``` to the test case ```test_searchConcept_searchWithWordAndPosInJson``` you will get the same exception locally (for the searchWithWordAndPosInJson test case, the noResults test cases still pass for some reason):
```
@Test
    public void test_searchConcept_searchWithWordAndPosInJson() throws Exception {

        final String output = IOUtils
                .toString(this.getClass().getClassLoader().getResourceAsStream("output/conceptWithWordAndPos.json"), "UTF-8");

        this.mockMvc
                .perform(MockMvcRequestBuilders.get("/ConceptSearch").param("word", "einstein").param("pos", "noun").param("concept_list", "VogonWeb Concepts")
                        .param("operator", SearchParamters.OP_AND).accept(MediaType.APPLICATION_JSON_VALUE))
                .andExpect(content().json(output, false)).andExpect(status().isOk());

    }
```

2019-10-24 18:25 UTC, jdamerow commented
test this please

2019-10-24 18:26 UTC, jdamerow commented
Jenkins, run integration tests please

2019-10-24 18:31 UTC, jdamerow commented
test this please

2019-10-24 18:34 UTC, jdamerow commented on Conceptpower+Spring/pom.xml
> -		<tomcat.server.id>TomcatServer</tomcat.server.id>
should not be deleted as it is breaking the build

2019-10-24 19:14 UTC, jdamerow commented
test this please

2019-10-24 19:23 UTC, jdamerow commented on Conceptpower+Spring/pom.xml
> -				</configuration>
can't be removed

2019-10-24 19:38 UTC, kkrish39 commented on Conceptpower+Spring/pom.xml
> -				</configuration>
Added it back

2019-10-24 20:12 UTC, merged