Bug/ccp 226
diging/conceptpower pull request #209
Opened 2020-09-08 18:23 UTC by kkrish39

2020-09-09 05:27 UTC, nowke approved these changes

2020-09-10 13:55 UTC, jdamerow commented
Make it so, Jenkins.

2020-09-10 14:05 UTC, jdamerow commented
a couple things:
- "Search on description" should be "Search in description field" and there should be no period afterwards
- when "Search in description field" is checked, word **and** description fields should be searched, not just description
- the pagination doesn't seem to pass the search in description flag

2020-09-15 19:12 UTC, jdamerow commented
Resolve conflicts please

2020-09-16 20:24 UTC, jdamerow requested changes

2020-09-16 20:24 UTC, jdamerow commented on Conceptpower+Spring/src/main/java/edu/asu/conceptpower/app/core/impl/ConceptManager.java
> +            fieldMap.put(SearchFieldNames.DESCRIPTION, word );
please follow our code style

2020-09-16 20:24 UTC, jdamerow commented
Make it so, Jenkins.

2020-09-16 20:31 UTC, jdamerow commented
something is wrong now (I think it's the use of the TermQuery). If I search for Einstein and the description checkbox is checked, it only finds one result (probably the one that has einstein in the description) and none of the others.

2020-09-16 21:18 UTC, kkrish39 commented
Can you check once? I searched with einstein with the checkbox checked. I got three rows.
<img width="1434" alt="Screen Shot 2020-09-16 at 2 17 15 PM" src="https://user-images.githubusercontent.com/55424824/93393448-64656100-f827-11ea-960a-6f58cf993132.png">

2020-09-21 19:23 UTC, jdamerow commented
Make it so, Jenkins.

2020-10-01 18:34 UTC, jdamerow commented
It's still only returned one result when searching on description. Did you reindex after you did the changes to the query?

2020-10-05 13:14 UTC, kkrish39 commented
> It's still only returned one result when searching on description. Did you reindex after you did the changes to the query?

Let me check once again!

2020-10-27 16:07 UTC, kkrish39 commented
> It's still only returned one result when searching on description. Did you reindex after you did the changes to the query?

I reindexed and tried once again. Without checkbox checked.
<img width="1440" alt="Screen Shot 2020-10-27 at 11 58 27 AM" src="https://user-images.githubusercontent.com/55424824/97328005-efd10980-184b-11eb-8943-0a14e16c669d.png">

With checkbox checked.
<img width="1436" alt="Screen Shot 2020-10-27 at 11 58 41 AM" src="https://user-images.githubusercontent.com/55424824/97328859-d3819c80-184c-11eb-92e7-8cce68572ad3.png">

2020-10-27 17:46 UTC, jdamerow commented
Exactly, the second search should not return fewer results but more. Why does it not find "Einstein's special theory of relativity"?

2020-10-27 19:24 UTC, kkrish39 commented
> Exactly, the second search should not return fewer results but more. Why does it not find "Einstein's special theory of relativity"?

I see what's happening and what is required. When you said the query should search "concept and description" I thought the combined search of both. 

Now the query is returning only the rows which contain the search term in both concept and description.

2020-10-27 19:30 UTC, jdamerow commented
ah, yes, it should be "OR" not "AND"

2020-12-17 23:03 UTC, kkrish39 commented
I'm pretty sure it can be handled a bit more graciously. Let me know your comments.

2021-01-06 21:37 UTC, ashmichheda approved these changes

2021-01-07 18:05 UTC, jdamerow requested changes

2021-01-07 18:05 UTC, jdamerow commented on Conceptpower+Spring/src/main/java/edu/asu/conceptpower/app/lucene/impl/LuceneUtility.java
> +                    buildQuery(occur, perFieldAnalyzerWrapper, qBuild, builder, luceneFieldAnnotation, searchString, isSearchOnDescription);
isn't the only thing you need to do, test if `isSearchOnDescription` is true and if search is the description field, then exclude or not exclude it here?

2021-01-07 18:05 UTC, jdamerow commented on Conceptpower+Spring/src/main/java/edu/asu/conceptpower/app/lucene/impl/LuceneUtility.java
> +                    buildQuery(occur, perFieldAnalyzerWrapper, qBuild, builder, luceneFieldAnnotation, searchString, isSearchOnDescription);
something like 
```
if (search.fieldName != SearchFieldNames.DESCRIPTION || isSearchOnDescription ) { // or however you get the filed name
 buildQuery(...)
}
```

2021-01-07 18:05 UTC, closed without merging